### ISSUE TITLE
Minimum Rust Version

### ISSUE THREAD

**Issue by Deedasmi** [George3d6/Inquisitor#14]
Do we care about maintaining some specific rust version? Or just 'will always work on stable'?

New stable (1.25) has a new `use` feature, but don't want to move us to it if we're looking to support some older version.

**Comment by George3d6** [comment]
Hmh, currently I have 1.23 on my machine. But I haven't updated packages in a good while.

I'm on arch myself so I should always have the latest stable rustc and I don't mind using nightly if it has a feature we really need.

Overall I'd say using latest stable rustc version is more than fine (I have the same approach for the front-end atm, using w/e features the latest stable chromium/Firefox provide).

Once we reach 1.0.0 maybe we should settle on a version, but for now using latest stable is fine by me

**Comment by Deedasmi** [comment]
Works for me.
