### ISSUE TITLE
Make agent and receptor lib re-export shared lib

### ISSUE THREAD

**Issue by Deedasmi** [George3d6/Inquisitor#23]
Plugins shouldn't depend on shared_lib. We can make agent_lib depend on shared_lib and re-export all the functions so that plugins can use them while only depending on agent_lib. Same with receptor_lib.

**Comment by George3d6** [comment]
Ah, agreed, I did think having shared_lib as an extra dep there felt quite ugly. Will make the change tomorrow in case you don't get around to it.
