### ISSUE TITLE
--config flag

### ISSUE THREAD

**Issue by Deedasmi** [George3d6/Inquisitor#27]
I think both agent and receptor would benefit from a run time configuration argument. Particularly since building currently overwrites existing configs.

**Comment by George3d6** [comment]
Agreed, will have to look into a good library for that. If you have any suggestions, shot.

**Comment by Deedasmi** [comment]
I've used clap-rs. It's a bit large and has a learning curve, but very feature rich and generates the help flag automatically.

**Comment by George3d6** [comment]
Alright, I'll try seeing how easy this is to accomplish using clap for the receptor. The only problem here is that I'd like the plugins' configuration to also be specifiable (in the form a of configuration directory, so I'd have to find a way to send that to plugins, maybe via new).

**Comment by Deedasmi** [comment]
Yeah, probably a Path argument on new to the directory. Let the plugin figure out the specific file though.
