### ISSUE TITLE
Cleanup for 0.3.1

### ISSUE THREAD

**Issue by George3d6** [George3d6/Inquisitor#32]
There's a bunch of stuff that needs some cleaning up before 0.3.1

- [x] Cleanup code in the endpoints 
- [x] Cleanup code in the new plugin
- [x] The addition of the "standard" config system to the receptor's and agent's `main.rs`
- [x]  Cleaning up useless (or rarely used dependencies)
- [x] Upgrading dependency versions to the latest usable ones
- [x] Standardizing naming across config files and coming up with better defaults for them
- [x] Cleaning up code in general (this is an ongoing issue, but the codebase has grown quite a lot and I want to try and shrink it a bit before the release)
- [ ] Documenting the code via comments inside the code (There's some annoying logic going on in there which I'd rather document).

**Comment by Deedasmi** [comment]
FYI, https://github.com/killercup/cargo-edit is a godsend for managing dependencies. Just run `cargo upgrade` and it'll upgrade all your dependencies, then you just have to make sure it still compiles ;)

**Comment by George3d6** [comment]
All done except for comments.

I'll move that part to 0.3.2 or 0.4
