### ISSUE TITLE
Comparator operator bug?

### ISSUE THREAD

**Issue by Deedasmi** [George3d6/Inquisitor#34]
While running clippy on the receptor, it pointed out this:

* https://github.com/George3d6/Inquisitor/blob/master/receptor/receptor_plugins/comparator/src/lib.rs#L147
* https://github.com/George3d6/Inquisitor/blob/master/receptor/receptor_plugins/comparator/src/lib.rs#L155

Both of these blocks are the same. Is the second one supposed to be an 'in' or like comparison?

**Comment by George3d6** [comment]
Pressumably the merge has fixed this.

**Comment by Deedasmi** [comment]
Nah, but the line numbers changed on we. Those entire blocks are the same. Your "contains" block does an equality check.

**Comment by Deedasmi** [comment]
Lot easier to see in the latest commit:

https://github.com/George3d6/Inquisitor/blob/master/receptor/receptor_plugins/comparator/src/lib.rs#L136

Lines 136-138 and 140-142 are identical despite being under different conditions. Was that intentional or is it a bug?

**Comment by George3d6** [comment]
Ups, that was indeed a bug, contains was meant to translate to .contains not ==, for some reason I had thought your pull request fixed that (my bad, I didn't look at it properly). Fixed it now
