### ISSUE TITLE
Supporting configs for non-local plugins

### ISSUE THREAD

**Issue by Deedasmi** [George3d6/Inquisitor#46]
The agent build script currently assumes that the included plugins are at a static path. Moving forward with allowing git paths and crates.io plugins, this doesn't work.

If plugins assume disabled upon not finding a configuration option, we could simply remove this behavior from the build script and distribute the config files as part of the tar ball. 

Touches #39

**Comment by George3d6** [comment]
It was more of a step to help with quickly building and prototyping. I agree it should be removed at some point before 0.4

**Comment by Deedasmi** [comment]
I have this done, I'll wait for 0.3.1 release before pushing.
