### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Deedasmi** [George3d6/Inquisitor#8]
Really needs some proper logging. My test environment isn't working and I'm not sure why. Do you have a preference on library?

**Comment by George3d6** [comment]
In my opinion [env_logger](https://doc.rust-lang.org/log/env_logger/) is the best choice at the moment. Mature enough and issue to use by virtue of not suffering from the pedantic design choices of slog/slogger.

I will probably add it and use it to replace some of the current logging on Wednesday, if you needed it before hand feel free to add it.

If you think another logger would work better, feel free to suggest one.

**Comment by Deedasmi** [comment]
I've only used slog. It's neat and powerful, but definitely a little complicated. Also the logger is an object you have to pass around, which isn't the nicest thing for our use case. I'd be interested in seeing how env_logger works across crate boundaries, but otherwise it works for me.

**Comment by George3d6** [comment]
Hmh, env_logger is, well, env based, so the same settings should apply no matter where you call it from (though I think there's ways to specify what to log and what to not log in the crate).

Overall I find it more convenient to use, and definitely easier to replace than something like slog, so for the early stages of software I think it's the best solution.

I will try to get it into the project to add some debug/error/info logs that I'd want to have there anyway and I think you will find it does the job quite alright.

**Comment by Deedasmi** [comment]
Agent logging isn't done yet

**Comment by George3d6** [comment]
Hmh, I closed the issue because I intorduced env_loger as the logger and assumed that this issue was more about "introducing a logger" rather than "Getting some proper logs", since the second will always be a moving goal. But feel free to close it whenever you are satisifed with the situation logging-wise or open a new open with more clear goals as to what should be logged and at what levels.
